# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c3b82b097d48fbc922893be9fc74ceba13a3b40180fbd6ebcd91f63c643e874ed687db89a5459199f6f586cfba944ca1625a6d7deb7bfb6d4dac8cb27ddf6203

test:
  secret_key_base: c28907cf105456b3d421722d343eaf3577933ac80c9b18bad20ea1dc0fcea4ae06898f5338a75640c6a8eeba965324fe309b00932a055c4d7b83f71768740f58

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
